name: JCEP CI

on: [ push, pull_request ]

jobs:

  backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurar JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Executar os testes
      run: mvn package -f ./JCEP-Backend/pom.xml


  frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './JCEP-Frontend/package-lock.json'
    - name: Executar os testes
      run: cd JCEP-Frontend && npm ci && npm run build --if-present && npm test -- --watch false
